### ISSUE TITLE
Is there a clerical error in Figure1？

### ISSUE THREAD

**Issue by yan-zhaoyu** [thuiar/TCL-MAP#1]
Dear authors，
I've read your arxiv paper, and as described in the "Representation Learning" part page 4, the **Augmented** sample Z~ (with ground truth label) is utilized Multimodal fusion layer MAG-BERT for semantic extraction, while BERT encoder for the normal sample Z(with the [MASK] token). But in Figure1, the order of these two process seems to be reversed. Is there any clerical error, or just my misunderstanding? Looking forward to your reply :-)

**Comment by zhougr18** [comment]
Thank you for pointing out the discrepancy in our paper. We apologize for the error in the "Representation Learning" part where the augmented sample Z~ (with ground truth label) and the normal sample Z (with the [MASK] token) were mistakenly described in reverse order. Figure 1 correctly shows the model structure. We will correct the mistake in the paper as soon as possible.

**Comment by yan-zhaoyu** [comment]
OK, thanks for respond :-)
